-- 결제 결과 복구를 위한 결제 시도 이력과 웹훅 수신함을 추가한다.
-- 애플리케이션 쓰기를 중단하고 PROCESSING 결제의 PG 상태를 확인한 뒤 한 번 적용한다.
BEGIN;
LOCK TABLE payments, orders IN SHARE ROW EXCLUSIVE MODE;

ALTER TABLE payments ADD COLUMN processing_operation varchar(30) NOT NULL DEFAULT 'NONE';
ALTER TABLE payments ADD COLUMN recovery_state varchar(30) NOT NULL DEFAULT 'NONE';
ALTER TABLE payments ADD COLUMN current_attempt_id varchar(50);
ALTER TABLE payments ADD COLUMN last_failure_code varchar(100);
ALTER TABLE payments ADD COLUMN last_verified_at timestamp;
ALTER TABLE payments ADD COLUMN state_version bigint NOT NULL DEFAULT 0;

-- 기존 처리 중 결제는 승인 시도로 간주하고 복구 워커가 PG 조회를 수행하게 한다.
UPDATE payments
SET processing_operation = CASE WHEN payment_status = 'PROCESSING' THEN 'CONFIRM' ELSE 'NONE' END,
    recovery_state = CASE WHEN payment_status = 'PROCESSING' THEN 'PENDING' ELSE 'NONE' END
WHERE processing_operation = 'NONE' AND recovery_state = 'NONE';

CREATE TABLE payment_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id varchar(50) NOT NULL,
    payment_id bigint NOT NULL,
    sequence_number integer NOT NULL,
    operation varchar(30) NOT NULL,
    attempt_status varchar(30) NOT NULL,
    source_attempt_id bigint,
    approval_attempt_id bigint,
    pg_order_id varchar(64) NOT NULL,
    payment_key varchar(255),
    amount bigint NOT NULL,
    cancel_reason varchar(100),
    request_hash varchar(128),
    pg_idempotency_key varchar(300) NOT NULL,
    pg_status varchar(100),
    pg_error_code varchar(100),
    failure_reason varchar(255),
    requested_at timestamp NOT NULL,
    completed_at timestamp,
    pg_approved_at timestamp,
    pg_canceled_at timestamp,
    next_check_at timestamp NOT NULL,
    check_count integer NOT NULL DEFAULT 0,
    state_version bigint NOT NULL DEFAULT 0,
    lease_token varchar(50),
    lease_until timestamp,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_payment_attempts_attempt_id UNIQUE (attempt_id),
    CONSTRAINT uk_payment_attempts_payment_sequence UNIQUE (payment_id, sequence_number),
    CONSTRAINT uk_payment_attempts_idempotency_key UNIQUE (pg_idempotency_key),
    CONSTRAINT uk_payment_attempts_source_operation UNIQUE (source_attempt_id, operation),
    CONSTRAINT fk_payment_attempts_payment FOREIGN KEY (payment_id) REFERENCES payments(id),
    CONSTRAINT fk_payment_attempts_source FOREIGN KEY (source_attempt_id) REFERENCES payment_attempts(id),
    CONSTRAINT fk_payment_attempts_approval FOREIGN KEY (approval_attempt_id) REFERENCES payment_attempts(id)
);
CREATE INDEX idx_payment_attempts_recovery ON payment_attempts (attempt_status, next_check_at, id);
CREATE INDEX idx_payment_attempts_payment_status ON payment_attempts (payment_id, attempt_status);

CREATE TABLE payment_webhook_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transmission_id varchar(100) NOT NULL,
    event_type varchar(50) NOT NULL,
    event_hash varchar(128) NOT NULL,
    pg_order_id varchar(64),
    payment_key varchar(255),
    pg_status varchar(30),
    pg_created_at timestamp,
    processing_status varchar(30) NOT NULL,
    receive_count integer NOT NULL DEFAULT 0,
    next_process_at timestamp NOT NULL,
    processed_at timestamp,
    failure_reason varchar(255),
    lease_token varchar(50),
    lease_until timestamp,
    received_at timestamp NOT NULL,
    CONSTRAINT uk_payment_webhook_events_transmission_id UNIQUE (transmission_id)
);
CREATE INDEX idx_payment_webhook_events_processing
    ON payment_webhook_events (processing_status, next_process_at, id);

-- 기존 PROCESSING 결제는 결정적 시도 ID로 한 건씩 이력을 만든다.
INSERT INTO payment_attempts (
    attempt_id, payment_id, sequence_number, operation, attempt_status, pg_order_id,
    payment_key, amount, pg_idempotency_key, requested_at, next_check_at,
    check_count, state_version, created_at, updated_at
)
SELECT 'LEGACY-' || p.payment_id, p.id, 1, 'CONFIRM', 'PROCESSING', o.order_number,
       p.payment_key, p.amount, 'legacy-confirm-' || p.payment_id,
       COALESCE(p.created_at, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP,
       0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE p.payment_status = 'PROCESSING';

UPDATE payments p
SET current_attempt_id = 'LEGACY-' || p.payment_id
WHERE p.payment_status = 'PROCESSING';

COMMIT;
