-- 결제 결과 복구를 위한 결제 시도 이력과 웹훅 수신함을 추가한다.
-- 애플리케이션 쓰기를 중단하고 백업 후 적용한다. 완료 표식이 있으면 재실행은 아무것도 변경하지 않는다.
BEGIN;
LOCK TABLE posts, orders, payments IN SHARE ROW EXCLUSIVE MODE;

DO $migration$
BEGIN
    IF to_regclass('payment_recovery_029_applied') IS NOT NULL THEN
        RETURN;
    END IF;

DO $$
BEGIN
    IF EXISTS (
        SELECT payment_key FROM payments WHERE payment_key IS NOT NULL
        GROUP BY payment_key HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION '결제 키가 중복된 결제가 있습니다. PG 결과를 확인하고 정리한 뒤 적용하세요.';
    END IF;
    IF EXISTS (SELECT 1 FROM payments WHERE payment_status = 'PROCESSING' AND payment_key IS NULL) THEN
        RAISE EXCEPTION '결제 키가 없는 PROCESSING 결제가 있습니다. PG 결과를 확인하고 정리한 뒤 적용하세요.';
    END IF;
    IF EXISTS (SELECT order_id FROM payments GROUP BY order_id HAVING count(*) > 1) THEN
        RAISE EXCEPTION '주문당 결제가 중복됩니다.';
    END IF;
    IF EXISTS (
        SELECT 1 FROM payments p JOIN orders o ON o.id = p.order_id
        WHERE p.amount <> o.amount
           OR (p.payment_status = 'PROCESSING' AND o.order_status NOT IN ('PENDING', 'PAID'))
           OR (p.payment_status = 'SUCCESS' AND (o.order_status <> 'PAID' OR p.payment_key IS NULL))
    ) THEN
        RAISE EXCEPTION '결제 금액 또는 주문 상태가 모순됩니다.';
    END IF;
END $$;

-- 구버전 Hibernate가 만든 payment_status CHECK만 확장한다. 다른 CHECK는 보존한다.
DECLARE
    status_constraint record;
BEGIN
    FOR status_constraint IN
        SELECT c.conname FROM pg_constraint c
        JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attname = 'payment_status'
        WHERE c.conrelid = 'payments'::regclass AND c.contype = 'c'
          AND c.conkey = ARRAY[a.attnum]::smallint[]
    LOOP
        EXECUTE format('ALTER TABLE payments DROP CONSTRAINT %I', status_constraint.conname);
    END LOOP;
END;
ALTER TABLE payments ADD CONSTRAINT ck_payments_recovery_status
    CHECK (payment_status IN ('READY', 'PROCESSING', 'SUCCESS', 'CANCELED', 'FAILED'));

ALTER TABLE payments ADD COLUMN processing_operation varchar(30) NOT NULL DEFAULT 'NONE';
ALTER TABLE payments ADD COLUMN recovery_state varchar(30) NOT NULL DEFAULT 'NONE';
ALTER TABLE payments ADD COLUMN current_attempt_id varchar(50);
ALTER TABLE payments ADD COLUMN last_failure_code varchar(100);
ALTER TABLE payments ADD COLUMN last_verified_at timestamp;
ALTER TABLE payments ADD COLUMN state_version bigint NOT NULL DEFAULT 0;

-- 기존 처리 중 결제는 승인 시도로 간주하고 복구 워커가 PG 조회를 수행하게 한다.
UPDATE payments
SET processing_operation = CASE WHEN payment_status = 'PROCESSING' AND EXISTS (
        SELECT 1 FROM orders o WHERE o.id = payments.order_id AND o.order_status = 'PAID'
    ) THEN 'CANCEL'
    WHEN payment_status = 'PROCESSING' THEN 'CONFIRM' ELSE 'NONE' END,
    recovery_state = CASE WHEN payment_status = 'PROCESSING' THEN 'PENDING' ELSE 'NONE' END
WHERE processing_operation = 'NONE' AND recovery_state = 'NONE';

CREATE TABLE payment_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id varchar(50) NOT NULL,
    payment_id bigint NOT NULL,
    sequence_number integer NOT NULL,
    operation varchar(30) NOT NULL,
    attempt_status varchar(30) NOT NULL,
    source_attempt_id bigint,
    approval_attempt_id bigint,
    pg_order_id varchar(64) NOT NULL,
    payment_key varchar(255),
    amount bigint NOT NULL,
    cancel_reason varchar(100),
    request_hash varchar(128),
    pg_idempotency_key varchar(300) NOT NULL,
    pg_status varchar(100),
    pg_error_code varchar(100),
    failure_reason varchar(255),
    requested_at timestamp NOT NULL,
    completed_at timestamp,
    pg_approved_at timestamp,
    pg_canceled_at timestamp,
    next_check_at timestamp NOT NULL,
    check_count integer NOT NULL DEFAULT 0,
    state_version bigint NOT NULL DEFAULT 0,
    lease_token varchar(50),
    lease_until timestamp,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_payment_attempts_attempt_id UNIQUE (attempt_id),
    CONSTRAINT uk_payment_attempts_payment_sequence UNIQUE (payment_id, sequence_number),
    CONSTRAINT uk_payment_attempts_idempotency_key UNIQUE (pg_idempotency_key),
    CONSTRAINT uk_payment_attempts_source_operation UNIQUE (source_attempt_id, operation),
    CONSTRAINT fk_payment_attempts_payment FOREIGN KEY (payment_id) REFERENCES payments(id),
    CONSTRAINT fk_payment_attempts_source FOREIGN KEY (source_attempt_id) REFERENCES payment_attempts(id),
    CONSTRAINT fk_payment_attempts_approval FOREIGN KEY (approval_attempt_id) REFERENCES payment_attempts(id)
);
CREATE INDEX idx_payment_attempts_recovery ON payment_attempts (attempt_status, next_check_at, id);
CREATE INDEX idx_payment_attempts_payment_status ON payment_attempts (payment_id, attempt_status);
CREATE UNIQUE INDEX uk_payment_attempts_confirm_pg_order_id
    ON payment_attempts (pg_order_id) WHERE operation = 'CONFIRM';
CREATE UNIQUE INDEX uk_payment_attempts_confirm_payment_key
    ON payment_attempts (payment_key) WHERE operation = 'CONFIRM' AND payment_key IS NOT NULL;
CREATE UNIQUE INDEX uk_payment_attempts_active_payment
    ON payment_attempts (payment_id)
    WHERE attempt_status IN ('PREPARED', 'PROCESSING', 'UNKNOWN');

CREATE TABLE payment_webhook_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transmission_id varchar(100) NOT NULL,
    event_type varchar(50) NOT NULL,
    event_hash varchar(128) NOT NULL,
    pg_order_id varchar(64),
    payment_key varchar(255),
    pg_status varchar(30),
    pg_created_at timestamp,
    processing_status varchar(30) NOT NULL,
    receive_count integer NOT NULL DEFAULT 0,
    next_process_at timestamp NOT NULL,
    processed_at timestamp,
    failure_reason varchar(255),
    lease_token varchar(50),
    lease_until timestamp,
    received_at timestamp NOT NULL,
    CONSTRAINT uk_payment_webhook_events_transmission_id UNIQUE (transmission_id)
);
CREATE INDEX idx_payment_webhook_events_processing
    ON payment_webhook_events (processing_status, next_process_at, id);

-- 기존 PROCESSING 결제는 결정적 시도 ID로 한 건씩 이력을 만든다.
INSERT INTO payment_attempts (
    attempt_id, payment_id, sequence_number, operation, attempt_status, pg_order_id,
    payment_key, amount, pg_idempotency_key, requested_at, next_check_at,
    check_count, state_version, created_at, updated_at
)
SELECT 'LEGACY-' || p.id, p.id, CASE WHEN o.order_status = 'PAID' THEN 2 ELSE 1 END,
       CASE WHEN o.order_status = 'PAID' THEN 'CANCEL' ELSE 'CONFIRM' END,
       'PROCESSING', o.order_number,
       p.payment_key, p.amount,
       CASE WHEN o.order_status = 'PAID' THEN 'cancel-' ELSE 'confirm-' END || p.payment_key,
       COALESCE(p.created_at, CURRENT_TIMESTAMP), CURRENT_TIMESTAMP,
       0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE p.payment_status = 'PROCESSING';

INSERT INTO payment_attempts (
    attempt_id, payment_id, sequence_number, operation, attempt_status, pg_order_id,
    payment_key, amount, pg_idempotency_key, requested_at, completed_at, pg_approved_at,
    next_check_at, check_count, state_version, created_at, updated_at
)
SELECT 'LEGACY-' || p.id, p.id, 1, 'CONFIRM',
       CASE WHEN p.payment_status = 'SUCCESS' THEN 'SUCCEEDED' ELSE 'PREPARED' END,
       o.order_number, p.payment_key, p.amount,
       CASE WHEN p.payment_status = 'SUCCESS' THEN 'confirm-' || p.payment_key ELSE 'confirm-LEGACY-' || p.id END,
       COALESCE(p.created_at, CURRENT_TIMESTAMP),
       CASE WHEN p.payment_status = 'SUCCESS' THEN p.approved_at ELSE NULL END,
       CASE WHEN p.payment_status = 'SUCCESS' THEN p.approved_at ELSE NULL END,
       CURRENT_TIMESTAMP, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE p.payment_status IN ('READY', 'SUCCESS');

-- 취소 중인 구 주문의 확정 승인 이력을 별도로 보존한다. 자동 취소 재전송은 하지 않는다.
INSERT INTO payment_attempts (
    attempt_id, payment_id, sequence_number, operation, attempt_status, pg_order_id,
    payment_key, amount, pg_idempotency_key, requested_at, completed_at, pg_approved_at,
    next_check_at, check_count, state_version, created_at, updated_at
)
SELECT 'LEGACY-APPROVAL-' || p.id, p.id, 1, 'CONFIRM', 'SUCCEEDED', o.order_number,
       p.payment_key, p.amount, 'confirm-' || p.payment_key,
       COALESCE(p.created_at, CURRENT_TIMESTAMP), p.approved_at, p.approved_at,
       CURRENT_TIMESTAMP, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM payments p JOIN orders o ON o.id = p.order_id
WHERE p.payment_status = 'PROCESSING' AND o.order_status = 'PAID';

UPDATE payment_attempts cancel_attempt
SET approval_attempt_id = approval.id
FROM payment_attempts approval
WHERE cancel_attempt.operation = 'CANCEL' AND approval.operation = 'CONFIRM'
  AND cancel_attempt.payment_id = approval.payment_id;

UPDATE payments p
SET current_attempt_id = 'LEGACY-' || p.id
WHERE p.payment_status IN ('READY', 'PROCESSING', 'SUCCESS');

CREATE TABLE payment_recovery_029_applied (
    applied_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO payment_recovery_029_applied DEFAULT VALUES;
END $migration$;
COMMIT;
