-- 매장과 요일별 영업시간의 조회용 스키마 및 입력 제약을 생성한다.
BEGIN;

CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    region VARCHAR(20) NOT NULL,
    address VARCHAR(500) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    phone VARCHAR(30),
    CONSTRAINT ck_stores_name CHECK (length(trim(name)) > 0),
    CONSTRAINT ck_stores_address CHECK (length(trim(address)) > 0),
    CONSTRAINT ck_stores_region CHECK (region IN (
        '서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종',
        '경기', '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주'
    )),
    CONSTRAINT ck_stores_latitude CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_stores_longitude CHECK (longitude BETWEEN -180 AND 180)
);
CREATE INDEX IF NOT EXISTS ix_stores_region_id ON stores(region, id);
CREATE INDEX IF NOT EXISTS ix_stores_latitude ON stores(latitude);

CREATE TABLE IF NOT EXISTS store_business_hours (
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    day_of_week VARCHAR(9) NOT NULL,
    open_time TIME,
    close_time TIME,
    closed BOOLEAN NOT NULL,
    CONSTRAINT uk_store_business_hours_day UNIQUE (store_id, day_of_week),
    CONSTRAINT ck_store_business_hours_day CHECK (day_of_week IN (
        'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'
    )),
    CONSTRAINT ck_store_business_hours_times CHECK (
        (closed AND open_time IS NULL AND close_time IS NULL)
        OR (NOT closed AND open_time IS NOT NULL AND close_time IS NOT NULL
            AND EXTRACT(SECOND FROM open_time) = 0 AND EXTRACT(SECOND FROM close_time) = 0
            AND open_time < TIME '24:00' AND close_time < TIME '24:00')
    )
);
COMMIT;
