-- 사용자별 관심 매장 관계와 중복 방지 제약 및 목록·집계 인덱스를 생성한다.
BEGIN;

CREATE TABLE IF NOT EXISTS store_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    store_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_store_favorites_user_store UNIQUE (user_id, store_id),
    CONSTRAINT fk_store_favorites_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_store_favorites_store FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_store_favorites_user_created_id ON store_favorites(user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_store_favorites_store ON store_favorites(store_id);

COMMIT;
