-- 이슈 #50의 기기 토큰·알림함·영속 발송 작업과 이력 스키마를 재실행 가능하게 만든다.
BEGIN;
CREATE TABLE IF NOT EXISTS device_tokens (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 token VARCHAR(2048) NOT NULL,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 platform VARCHAR(16) NOT NULL CHECK(platform IN ('ANDROID','IOS','WEB')),
 active BOOLEAN NOT NULL,
 ownership_version BIGINT NOT NULL,
 CONSTRAINT uk_device_tokens_token UNIQUE(token)
);
CREATE INDEX IF NOT EXISTS ix_device_tokens_user_active ON device_tokens(user_id,active,id);
CREATE TABLE IF NOT EXISTS notifications (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 event_key VARCHAR(150) NOT NULL,
 type VARCHAR(32) NOT NULL CHECK(type IN ('CHAT_MESSAGE','PAYMENT_SUCCESS','PAYMENT_CANCELED')),
 title VARCHAR(100) NOT NULL,
 target_id VARCHAR(100) NOT NULL,
 created_at TIMESTAMP NOT NULL,
 read_at TIMESTAMP,
 CONSTRAINT uk_notifications_event_user UNIQUE(event_key,user_id)
);
CREATE INDEX IF NOT EXISTS ix_notifications_user_created ON notifications(user_id,created_at DESC,id DESC);
CREATE TABLE IF NOT EXISTS push_deliveries (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
 device_token_id BIGINT NOT NULL REFERENCES device_tokens(id) ON DELETE CASCADE,
 ownership_version BIGINT NOT NULL,
 status VARCHAR(16) NOT NULL CHECK(status IN ('PENDING','SENT','FAILED','SKIPPED')),
 attempts INTEGER NOT NULL CHECK(attempts>=0),
 next_attempt_at TIMESTAMP NOT NULL,
 last_code VARCHAR(100),
 provider_message_id VARCHAR(512),
 CONSTRAINT uk_push_delivery_notification_device UNIQUE(notification_id,device_token_id)
);
CREATE INDEX IF NOT EXISTS ix_push_delivery_due ON push_deliveries(status,next_attempt_at,id);
CREATE TABLE IF NOT EXISTS push_attempts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 delivery_id BIGINT NOT NULL REFERENCES push_deliveries(id) ON DELETE CASCADE,
 attempt_number INTEGER NOT NULL,
 result_code VARCHAR(100) NOT NULL,
 attempted_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_push_attempt_delivery ON push_attempts(delivery_id,id);
COMMIT;
