-- 사용자별 관심 상품 관계와 중복 방지 제약 및 목록·집계 인덱스를 생성한다.
BEGIN;

CREATE TABLE IF NOT EXISTS post_favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_post_favorites_user_post UNIQUE (user_id, post_id),
    CONSTRAINT fk_post_favorites_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_favorites_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_post_favorites_user_created_id ON post_favorites(user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_post_favorites_post ON post_favorites(post_id);

COMMIT;
