-- 방향성 사용자 팔로우 관계와 참조·중복·자기 관계 제약 및 목록 인덱스를 생성한다.
BEGIN;

CREATE TABLE IF NOT EXISTS user_follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL,
    following_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_follows_direction UNIQUE (follower_id, following_id),
    CONSTRAINT ck_user_follows_not_self CHECK (follower_id <> following_id),
    CONSTRAINT fk_user_follows_follower FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_follows_following FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_user_follows_follower_created_id ON user_follows(follower_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_user_follows_following_created_id ON user_follows(following_id, created_at DESC, id DESC);

COMMIT;
