-- 구매 확정 거래 후기의 주문 스냅샷 관계와 중복·평점 제약을 구성한다.
BEGIN;
LOCK TABLE orders IN SHARE ROW EXCLUSIVE MODE;

CREATE UNIQUE INDEX IF NOT EXISTS uk_orders_review_participants ON orders (id, user_id, seller_id);

CREATE TABLE IF NOT EXISTS transaction_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    content VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT fk_reviews_order_participants FOREIGN KEY (order_id, buyer_id, seller_id)
        REFERENCES orders (id, user_id, seller_id),
    CONSTRAINT fk_reviews_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_reviews_recipient FOREIGN KEY (recipient_id) REFERENCES users (id),
    CONSTRAINT uk_reviews_order_author UNIQUE (order_id, author_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_content CHECK (length(trim(content)) > 0),
    CONSTRAINT ck_reviews_participants CHECK (
        author_id <> recipient_id AND
        ((author_id = buyer_id AND recipient_id = seller_id) OR
         (author_id = seller_id AND recipient_id = buyer_id))
    )
);
CREATE INDEX IF NOT EXISTS ix_reviews_recipient_created_id
    ON transaction_reviews (recipient_id, created_at DESC, id DESC);
COMMIT;
