// 프로필 PostgreSQL 검증마다 독립 스키마를 만들고 수동 변경 SQL을 실행한다.
package com.kitschcatch.backend.domain.user;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.UUID;

final class PostgresProfileTestDatabase implements AutoCloseable {

	final String schema = "issue31_" + UUID.randomUUID().toString().replace("-", "");
	final String url = System.getenv("ISSUE31_TEST_DB_URL");
	final String username = System.getenv().getOrDefault("ISSUE31_TEST_DB_USERNAME", "postgres");
	final String password = System.getenv().getOrDefault("ISSUE31_TEST_DB_PASSWORD", "");

	PostgresProfileTestDatabase() throws SQLException {
		try (Connection connection = DriverManager.getConnection(url, username, password);
			 var statement = connection.createStatement()) {
			statement.execute("CREATE SCHEMA " + schema);
		}
	}

	Connection connect() throws SQLException {
		Connection connection = DriverManager.getConnection(url, username, password);
		connection.setSchema(schema);
		return connection;
	}

	void createLegacyUsers(Connection connection) throws SQLException {
		try (var statement = connection.createStatement()) {
			statement.execute("""
				CREATE TABLE users (
				    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				    nickname VARCHAR(50) NOT NULL,
				    email VARCHAR(255) NOT NULL UNIQUE,
				    auth_provider VARCHAR(30) NOT NULL,
				    provider_user_id VARCHAR(100) NOT NULL,
				    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
				    CONSTRAINT uk_users_auth_provider_provider_user_id
				        UNIQUE (auth_provider, provider_user_id)
				)
				""");
		}
	}

	static void migrate(Connection connection) throws SQLException, IOException {
		try (var stream = PostgresProfileTestDatabase.class.getResourceAsStream("/db/manual/031_user_profile.sql");
			 var statement = connection.createStatement()) {
			if (stream == null) {
				throw new IOException("031_user_profile.sql 파일이 없습니다.");
			}
			try {
				statement.execute(new String(stream.readAllBytes(), StandardCharsets.UTF_8));
			} catch (SQLException exception) {
				statement.execute("ROLLBACK");
				throw exception;
			}
		}
	}

	@Override
	public void close() throws SQLException {
		try (Connection connection = connect(); var statement = connection.createStatement()) {
			statement.execute("DROP SCHEMA " + schema + " CASCADE");
		}
	}
}
